# Generated by Django 2.2.3 on 2019-07-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='identity',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='nome',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='pjtId',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='projeto',
            name='hubId',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='projeto',
            name='identity',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='projeto',
            name='nome',
            field=models.CharField(default='', max_length=300),
        ),
    ]
